LabProject/Areas/User/Controllers/SimilarTestLabsController.cs
using LabProject.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LabProject.Areas.User.Controllers
{
    public class SimilarTestLabsController : Controller
    {
        static List<BookTest> lstBooktest = new List<BookTest>();
        readonly LabDataBaseEntities labEntity = new LabDataBaseEntities();
        Random rnd = new Random();
        [HttpGet]
        // GET: User/SimilarTestLabs
        public ActionResult Index(int testId)
        {
            List<TestLab> testlab;
            testlab = (from labt in labEntity.TestLabPrices
                       join lab in labEntity.LabDetails on labt.LabId equals lab.LabId
                       join t in labEntity.Tests on labt.TestId equals t.Testid
                       where labt.TestId == testId
                       select new TestLab
                       {
                           testLabId = labt.TestLabId,
                           tests = t,
                           Labs = lab,
                           Price = labt.Price
                       }).ToList();
            return View(testlab);
        }

        public ActionResult RegisterOrLogin()
        {
            return View();
        }

        public int BookTest(BookTest bookTest)
        {
            bookTest.UserId =Convert.ToInt32(Request.Cookies["userId"].Value);
            lstBooktest.Add(bookTest);
            Session["lstBookTest"] = lstBooktest;
            return 0;
        }
    }
}

LabProject/Areas/User/Views/SimilarTestLabs/Index.cshtml
@model IEnumerable<LabProject.Models.ViewModel.TestLab>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/User/Views/Shared/_LayoutUser.cshtml";
}

<input type="hidden" value="user11" id="username" />

@using (Html.BeginForm("Index", "LabTest", FormMethod.Get))
{
    @Model.First().tests.TestName;
    <div class="table-responsive">
        <table class="table">
            <th>
                lab Name
            </th>
            <th>
                Price
            </th>
            <th>
                Book Test
            </th>
            @foreach (var tp in Model)
            {
                <tr>

                    <td>@tp.Labs.LabName </td>
                    <td>@tp.Price </td>
                    <td>
                        <button type="button" class="btn btn-default btn-lg myBtn" data-assigned-id="@tp.testLabId" id="myBtn_@tp.testLabId">Book Test</button>
                    </td>
                </tr>
            }

        </table>
        <div class="container">

            <!-- Modal -->
            <div class="modal fade" id="myModal" role="dialog">
                <div class="modal-dialog">

                    <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-head" style="padding:35px 50px;">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h3><span class="glyphicon glyphicon-eye-open"></span>Login to Book Your Test</h3>
                        </div>
                        <div class="modal-body" style="padding:40px 50px;">
                            <form role="form">
                                <div class="form-group">
                                    <label for="usrname"><span class="glyphicon glyphicon-user"></span> Username</label>
                                    <input style="width:100%!important" type="text" class="form-control" id="usrname" placeholder="Enter email">
                                </div>
                                <div class="form-group">
                                    <label for="psw"><span class="glyphicon glyphicon-eye-open"></span> Password</label>
                                    <input type="text" class="form-control" id="psw" placeholder="Enter password">
                                </div>
                                <div class="checkbox">
                                    <label><input type="checkbox" value="" checked>Remember me</label>
                                </div>
                                <button type="submit" class="btn btn-success btn-block"><span class="glyphicon glyphicon-off"></span> Login</button>
                            </form>
                        </div>
                        <div class="modal-footer">
                            <p>Not a member? <a href="#">Sign Up</a></p>
                            <p>Forgot <a href="#">Password?</a></p>
                        </div>
                    </div>

                </div>
            </div>
        </div>

    </div>
}

<script>
    $(document).ready(function () {
        $(".myBtn").click(function () {
            var TestLabId = $(this).data('assigned-id'); 3
            
            if ($('#username').val() != 'user') {
                callAction(TestLabId,this);
            }
            else {
                $("#myModal").modal();
            }

        });

        function callAction(TestLabId,btn) {
            var bookTest = {};
            bookTest.UserId = 1;
            bookTest.TestLabId = TestLabId;
            $.ajax({
                // edit to add steve's suggestion.
                //url: "/ControllerName/ActionName",
                type: "POST",
                url: '@Url.Action("BookTest", "SimilarTestLabs")',
                data: '{bookTest: ' + JSON.stringify(bookTest) + '}',
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (data) {
                    $(btn).html('Selected').css('background-color', 'red').css('color', 'white').attr('disabled', true);
                   
                }
            });
        }

    });

    function CreateGuid() {
        function _p8(s) {
            var p = (Math.random().toString(16) + "000000000").substr(2, 8);
            return s ? "-" + p.substr(0, 4) + "-" + p.substr(4, 4) : p;
        }
        return _p8() + _p8(true) + _p8(true) + _p8();
    } 
</script>
<style>

    .modal-head {
        display: -ms-flexbox;
        -ms-flex-align: start;
        /* align-items: flex-start; */
        -ms-flex-pack: justify;
        justify-content: space-between;
        padding: 1rem 1rem;
        border-bottom: 1px solid #dee2e6;
        border-top-left-radius: 0.3rem;
        border-top-right-radius: 0.3rem;
        background-color: #28a745;
        color:white;
    }
    .text-center {
        text-align:left!important;
    }
</style>

LabProject/Areas/User/Views/SimilarTestLabs/RegisterOrLogin.cshtml
@{
    ViewBag.Title = "RegisterOrLogin";
    Layout = "~/Areas/User/Views/Shared/_LayoutUser.cshtml";
}

<h2>RegisterOrLogin</h2>

<div id="loginModal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header" style=" display:block!important">
                <h3 class="float-left">Login</h3>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">
                <form class="form" role="form" autocomplete="off" id="formLogin" novalidate="" method="POST">
                    <div class="form-group">
                        <a href="" class="float-right">New user?</a>
                        <label for="uname1">Username</label>
                        <input type="text" class="form-control form-control-lg" name="uname1" id="uname1" required="">
                        <div class="invalid-feedback">Oops, you missed this one.</div>
                    </div> 
                    <div class="form-group">
                        <label>Password</label>
                        <input type="password" class="form-control form-control-lg" id="pwd1" required="" autocomplete="new-password">
                        <div class="invalid-feedback">Enter your password too!</div>
                    </div>
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="rememberMe">
                        <label class="custom-control-label" for="rememberMe">Remember me on this computer</label>
                    </div>
                    <div class="form-group py-4">
                        <button class="btn btn-outline-secondary btn-lg" data-dismiss="modal" aria-hidden="true">Cancel</button>
                        <button type="submit" class="btn btn-success btn-lg float-right" id="btnLogin">Login</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-12 text-center py-2">
            <a href="#loginModal" role="button" class="btn btn-primary btn-lg" data-toggle="modal">Login</a>
        </div>
    </div>
</div>