LabProject/LabProject/Controllers/LabController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LabProject.Controllers
{
    public class LabController : Controller
    {
        LabDataBaseEntities labEntity = new LabDataBaseEntities();
        [HttpGet]
        public ActionResult Index()
        {
            return View();

           
        }
        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.State = new SelectList(labEntity.States, "StateId", "StateName");
            return View("AddLab");
        }
        [HttpPost]
        public JsonResult  Create1(LabDetail LabDetails)
        {
            using (LabDataBaseEntities labEntity=new LabDataBaseEntities())
            {
                labEntity.LabDetails.Add(LabDetails);
                labEntity.SaveChanges();
            }
            return Json(LabDetails);
        }


        [HttpPost]
        public ActionResult Create(LabDetail LabDetails)
        {
            using (LabDataBaseEntities labEntity = new LabDataBaseEntities())
            {
                labEntity.LabDetails.Add(LabDetails);
                labEntity.SaveChanges();
            }
            return View();
        }
        public ActionResult UpdateLab(LabDetail lab)
        {
            using (LabDataBaseEntities entity = new LabDataBaseEntities())
            {
                LabDetail labd = entity.LabDetails.FirstOrDefault(x => x.LabId == lab.LabId);
                labd.LabName = lab.LabName;
                labd.LabOwnerName = lab.LabOwnerName;
                labd.Email = lab.Email;
                labd.ContactNumber = lab.ContactNumber;
                labd.About = lab.About;
                entity.SaveChanges();
            }
            return new EmptyResult();
        }
    }
}

LabProject/LabProject/Views/Lab/AddLab.cshtml
@model LabProject.Models.ViewModel.VMLabDetails

@{
    ViewBag.Title = "AddLab";

}

<h2>AddLab</h2>
@using (Html.BeginForm("Create","Lab")) {
<div class="row">
    <div class="col-sm-3"></div>
    <div class="col-sm-3">

        <div class="form-group">
            <label for="Name">Lab Name</label>
            <input type="text" class="form-control" id="LabName" name="LabName" placeholder="Name">
        </div>
        <div class="form-group">
            <label for="LabOwnerName">Lab Owner Name</label>
            <input type="text" class="form-control" id="LabOwnerName" name="LabOwnerName" placeholder="Owner Name">
        </div>
        <div class="form-group">
            <label for="Email1">Email</label>
            <input type="email" class="form-control" id="Email" name="email" placeholder="Email">
        </div>
        <div class="form-group">
            <label for="ContactNumber">Contact Number</label>
            <input type="text" class="form-control" id="ContactNumber" placeholder="Contact Number">
        </div>
        <div class="form-group">
            <label for="Add1">Add1</label>
            <input type="text" class="form-control" id="ContactNumber" placeholder="Email">
        </div>
        <div class="form-group">
            <label for="Add2">Add2</label>
            <input type="text" class="form-control" id="ContactNumber" placeholder="Email">
        </div>
        <div class="form-group">
            <label for="Add3">Add3</label>
            <input type="text" class="form-control" id="ContactNumber" placeholder="Email">
        </div>
        <div class="form-group">
            <label for="ContactNumber">State</label>
          @Html.DropDownListFor(x => x.State, (IEnumerable<SelectListItem>)ViewBag.State)

        </div>
       

    </div>View
    <div class="col-sm-3">

        <div class="form-group">
            <label for="ContactNumber">City</label>
            <select class="form-control">
                <option>1</option>
                <option>2</option>
                <option>3</option>
            </select>
        </div>
        
       <input type="submit" value="Create" />
      
    </div>

    <p>
       @Html.ActionLink("Create New", "Create")
    </p>
</div>
}

<script type="text/javascript">
        $(function () {
            $("#btnAdd").click(function () {

                var LabDetails = {};

                LabDetails.
                $.ajax({
                    type: "POST",
                    url: "/Lab/InsertLab",
                    data: '{LabDetails: ' + JSON.stringify(LabDetails) + '}',
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    success: function (response) {
                        
                    },
                    failure: function (response) {
                        alert(response.responseText);
                    },
                    error: function (response) {
                        alert(response.responseText);
                    }
                });
            });
        });
</script>

LabProject/LabProject/Views/Lab/Index.cshtml
@{
    ViewBag.Title = "Index";
   
}

<h2>Index</h2>