LabProject/Models/ViewModel/TestLab.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LabProject.Models.ViewModel
{
    public class TestLab
    {
       
        public int testLabId { get; set; }
        public IEnumerable<LabDetail> labId { get; set; }
        public IEnumerable<Test> testId { get; set; }
        public decimal? Price { get; set; }

        public Test tests { get; set; }
        public LabDetail Labs { get; set; }

    }
}

LabProject/Controllers/TestController.cs
    using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LabProject.Models.ViewModel;

namespace LabProject.Controllers
{
    public class TestController : Controller
    {
       
        LabDataBaseEntities labEnity = new LabDataBaseEntities();
        // GET: Test
        public ActionResult Index()
        {
            List<Test> tests = labEnity.Tests.ToList();
            return View(tests);
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult Create(Test test)
        {
            labEnity.Tests.Add(test);
            labEnity.SaveChanges();
            return View();
        }

        [HttpGet]
        public ActionResult Index(string Search_Data)
        {

            List<Test> testView = null;
            if (Search_Data == "" || Search_Data == null)
            {
                testView = labEnity.Tests.ToList();

            }
            else
            {
                testView = labEnity.Tests.Where(x => x.TestName.StartsWith(Search_Data)).ToList();
            }
            return View(testView);
        }

        [HttpGet]
        public ActionResult Edit(int testId)
        {
           VMTest tests = (from t in labEnity.Tests
                                where t.Testid == testId
                                select new VMTest
                                {
                                    TestName = t.TestName,
                                    TestReportDuration = t.TestReportDuration,
                                    PreRequisite = t.PreRequisite
                                }).ToList().FirstOrDefault();
            return View(tests);
        }


        [HttpPost]
        public ActionResult Edit(Test tst)
        {
            Test test = labEnity.Tests.FirstOrDefault(x => x.Testid == tst.Testid);
            test.TestName = tst.TestName;
            test.TestReportDuration = tst.TestReportDuration;
           
            return RedirectToAction("Index");
        }
    }


}

LabProject/Controllers/TestLabController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LabProject.Models.ViewModel;

namespace LabProject.Controllers
{
    public class TestLabController : Controller
    {
        LabDataBaseEntities labEntity = new LabDataBaseEntities();
        // GET: TestLab
        public ActionResult Index()
        {
            List<TestLab> testlab;
            testlab = (from labt in labEntity.TestLabPrices
                       join lab in labEntity.LabDetails on labt.LabId equals lab.LabId
                       join t in labEntity.Tests on labt.TestId equals t.Testid
                       select new TestLab
                       {
                           testLabId=labt.TestLabId,
                           tests = t,
                           Labs =lab,
                           Price=labt.Price
                           }).ToList();
           return View(testlab);
        }

        public ActionResult Create()
        {
            ViewBag.labId = new SelectList(labEntity.LabDetails, "LabId", "LabName", "--Select One--");
            ViewBag.testid = new SelectList(labEntity.Tests, "TestId", "testName", "--Select One--");
            return View();
        }

        [HttpPost]
        public ActionResult Create(TestLabPrice testLab)
        {
            ViewBag.labId = new SelectList(labEntity.LabDetails, "LabId", "LabName", "--Select One--");
            ViewBag.testid = new SelectList(labEntity.Tests, "TestId", "testName", "--Select One--");
            labEntity.TestLabPrices.Add(testLab);
            labEntity.SaveChanges();
            return View();
        }

        public ActionResult Edit(int testLabId)
        {
            ViewBag.labs = new SelectList(labEntity.LabDetails, "LabId", "LabName", "--Select One--");
            ViewBag.tests = new SelectList(labEntity.Tests, "TestId", "testName", "--Select One--");
            TestLab testlab;
            testlab = (from labt in labEntity.TestLabPrices
                       join lab in labEntity.LabDetails on labt.LabId equals lab.LabId
                       join t in labEntity.Tests on labt.TestId equals t.Testid
                       where labt.TestLabId== testLabId
                       select new TestLab
                       {
                           testLabId=labt.TestLabId,
                           tests = t,
                           Labs = lab,
                           Price = labt.Price
                       }).ToList().FirstOrDefault();
            return View(testlab);
           
        }

        [HttpPost]
        public ActionResult Edit(TestLab testLab)
        {
            TestLabPrice tl =labEntity.TestLabPrices.FirstOrDefault(x => x.TestLabId == testLab.testLabId);
            tl.Price = testLab.Price;
            labEntity.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

LabProject/Views/TestLab/Create.cshtml
@model LabProject.Models.ViewModel.TestLab
@{
                /**/

                ViewBag.Title = "Create";

}

<h2>Set Test Price</h2>


@using (Html.BeginForm())
{
    
    <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-3">
            <div class="form-group">
                <label for="ContactNumber">Labs</label>
                @Html.DropDownListFor(x => x.labId, (IEnumerable<SelectListItem>)ViewBag.labId, "Select One", new { id = "ddlLabs", @class = "form-control" })

            </div>
            <div class="form-group">
                <label for="ContactNumber">Tests</label>
                @Html.DropDownListFor(x => x.testId, (IEnumerable<SelectListItem>)ViewBag.testid, "Select One", new { id = "ddlTests", @class = "form-control" })

            </div>
            <div class="form-group">
                <label for="ContactNumber">Price</label>
                @Html.TextBoxFor(x => x.Price, new { id = "txtPrice", @class = "form-control" })

            </div>
            <div class="form-group">
               <input type="submit" value="Submit" class="form-control bg-success" />
            </div>
        </div>
        </div>
        
 }

LabProject/Views/TestLab/Edit.cshtml
@model LabProject.Models.ViewModel.TestLab

@{
    
}

<!DOCTYPE html>


<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
    <div class="form-horizontal">
        <h4>TestLab</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.testLabId)
        <div class="form-group">
            @Html.LabelFor(model => model.Labs, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Labs, (IEnumerable<SelectListItem>)ViewBag.labs, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Labs, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.tests, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.tests, (IEnumerable<SelectListItem>)ViewBag.tests, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tests, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-info" />
            </div>
        </div>
    </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

LabProject/Views/TestLab/Index.cshtml
@model IEnumerable<LabProject.Models.ViewModel.TestLab>
@{

    ViewBag.Title = "Index";
}

<h2>Index</h2>
@using (Html.BeginForm("Index", "LabTest", FormMethod.Get))
{
    <div class="form-group">
        @Html.TextBox("Search_Data", ViewBag.FilterValue as string)
        <input type="submit" value="Search" /> <input value="Add Price" type="button" class="btn btn-info btn-circle-xl m-166" onclick="location.href='@Url.Action("Create", "Test")'" />

    </div>
    <div class="table-responsive">
        <table class="table">
            <th>
                Test Name
            </th>
            <th>
                lab Name
            </th>
            <th>
                Price
            </th>
            @foreach (var tp in Model)
            {
            <tr>
                <td>@tp.testLabId</td>
                <td>@tp.tests.TestName</td>
                <td>@tp.Labs.LabName </td>
                <td>@tp.Price </td>
                <td><input value="Edit Lab" type="button" class="btn btn-info btn-circle-xl m-166" onclick="location.href='@Url.Action("Edit", "TestLab", new {testLabId=tp.testLabId} )'" /></td>
            </tr>
            }



        </table>
    </div>
}